version: '3.4'

services:
  koel:
    image: 0xcaff/koel
    depends_on:
      - database
    ports:
      - 80:80
    environment:
      DB_CONNECTION: mysql
      DB_HOST: database
      DB_USERNAME: koel
      DB_PASSWORD: koel
      DB_DATABASE: koel
    volumes:
      - music:/music
      - covers:/var/www/html/public/img/covers

  database:
    image: mysql/mysql-server:5.7
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: koel
      MYSQL_USER: koel
      MYSQL_PASSWORD: koel

volumes:
  db:
    driver: local

  music:
    driver: local

  covers:
    driver: local
